name: afyamap_kenya
description: AfyaMap - Comprehensive Kenya Hospital Locator with real-time availability and emergency services

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Backend & Database
  supabase_flutter: ^2.5.0
  sqflite: ^2.3.3+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Location & Maps
  geolocator: ^12.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.0.2
  
  # HTTP & Networking
  dio: ^5.4.0
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^1.0.0+1
  
  # UI & Navigation
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  # Notifications & Communication
  flutter_local_notifications: ^17.2.3
  url_launcher: ^6.2.5
  permission_handler: ^11.3.1
  share_plus: ^7.2.2
  
  # Utilities
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  csv: ^6.0.0
  
  # Performance & Analytics
  firebase_core: ^2.27.0
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.15
  
  # Accessibility & UI Enhancement
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/data/
  
