name: clinic_finder
description: A Flutter-based Clinic Finder App for Kenya
version: 1.0.0
environment:
  sdk: '>=3.0.0 <=3.8.1'  # Matches your Dart 3.8.1 version
dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0  # Updated to latest compatible version
  flutter_map: ^7.0.2  # Updated to latest compatible version
  sqflite: ^2.3.3+1  # Updated to latest compatible version
  flutter_local_notifications: ^17.2.3  # Updated to latest compatible version
  flutter_localizations:
    sdk: flutter
  latlong2: ^0.9.1  # Required by flutter_map
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:
  generate: true
  uses-material-design: true